language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

script:
  - composer create-project yiisoft/yii2-app-basic basic 2.0.8
  - phpunit --coverage-text ./tests/bootstrap.php ./tests/src


