language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

script:
  - composer require yidas/yii2-composer-bower-skip
  - composer require phpunit/phpunit ^5.0
  - composer require satooshi/php-coveralls '~1.0'
  - composer create-project --prefer-dist yiisoft/yii2-app-basic ./tests/app
  - mkdir -p build/logs
  - phpunit

after_success:
  - travis_retry php vendor/bin/coveralls