language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

script:
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer create-project --prefer-dist yiisoft/yii2-app-basic ./tests/app
  - phpunit --coverage-text --bootstrap ./tests/bootstrap.php ./tests/src